var biTurboProps={debug:!0,pauseAll:!1,minDelay:.15,instantDelay:.1};if("undefined"===typeof biTurbo)var biTurbo={};biTurbo.proto={debug:!1,pauseThis:!1,loop:0,height:0,width:0,insertionPoint:"",currentFrameIndex:0,timeLine:[],imagesToLoad:[],elementsCreated:[],limitToWaitPreload:25,addImagesToPreloadQueue:!0};
biTurbo.proto.initStyle=function(){var a=document.createElement("style");a.type="text/css";a.appendChild(document.createTextNode(""));document.head.appendChild(a);this.a_print("\n                               biTurbo.js \n \n                                  by \n \n                         \u00c1ngel Quijada \u00c1lvarez \n \n   A lightweight JS animation library for fast banner ads development! \n ");this.createTween("default_instant",biTurboProps.instantDelay,5)};
biTurbo.proto.writeClass=function(a,b){var c=document.createElement("style");c.type="text/css";a=this.defaultParameter(a,"");b=this.defaultParameter(b,"");document.getElementsByTagName("head")[0].appendChild(c);this.a_print("new CSS class : "+a+" : "+b);c.sheet.insertRule(a+"{"+b+"}",0)};
biTurbo.proto.createClass=function(a,b){var c="";if(1>arguments.length)this.a_print("Error: createClass: no parameters");else{var d=arguments[0];var e=arguments[1];this.isParameterDefined(e)&&(c+=e+" ; ");this.writeClass("."+d,c)}};biTurbo.proto.applyClass=function(a,b){b=this.defaultParameter(b,"");a=this.getDomElement(a);a.classList.add(b)};
biTurbo.proto.applyClassToAll=function(a){var b,c=this.elementsCreated.length;a=this.defaultParameter(a,"");for(b=0;b<c;b++){var d=this.getDomElement(this.elementsCreated[b]);this.applyClass(d,a)}};
biTurbo.proto.tweenClass=function(a,b,c,d){var e="",f=this;c=this.defaultParameter(c,biTurboProps.instantDelay);c+=biTurboProps.minDelay;d=this.defaultParameter(d,"default_instant");e="tween_"+d;a=this.getDomElement(a);var g=a.id;setTimeout(function(){!1===biTurboProps.pauseAll&&!1===f.pauseThis&&(a.className="",f.applyClass(a,g),f.applyClass(a,b),f.applyClass(a,e))},1E3*c)};
biTurbo.proto.animateClass=function(a,b){var c,d=0;a=this.getDomElement(a);if(void 0===b||1>b.length)this.a_print("animateClass error: no keyframes array");else{var e=b.length;this.a_print("animateClass keyframes for "+a.id+": "+e);for(c=0;c<e;c++){var f=b[c][0];if(!0===this.isParameterDefined(b[c][1])){var g=b[c][1];g-=biTurboProps.minDelay}else g=d;g+=biTurboProps.minDelay;g===d&&(g+=biTurboProps.minDelay);d=g=Math.round(100*g)/100;var h=!0===this.isParameterDefined(b[c][2])?b[c][2]:"default_instant";
this.a_print("animateClass keyframe["+c+"]: "+f+" , "+g+" , "+h);this.tweenClass(a,f,g,h)}}};biTurbo.proto.multipleClearClass=function(a){var b,c=a.length;for(b=0;b<c;b++)this.clearClass(a[b])};biTurbo.proto.clearClass=function(a){a=this.getDomElement(a);var b=a.id;a.className="";this.applyClass(a,b)};biTurbo.proto.clearClassToAll=function(){var a,b=this.elementsCreated.length;for(a=0;a<b;a++){var c=this.getDomElement(this.elementsCreated[a]);this.clearClass(c)}};
biTurbo.proto.CSS=function(a){var b="",c=1,d=1,e=0,f=!1,g=a.a,h=a.l,m=a.t,k=a.x,l=a.y,n=a.w,p=a.h,q=a.r,r=a.s,t=a.sx;a=a.sy;!0===this.isParameterDefined(g)&&(b+="opacity: "+g+" ; ");!0===this.isParameterDefined(n)&&(b+="width: "+n+"px ; ");!0===this.isParameterDefined(p)&&(b+="height: "+p+"px ; ");!0===this.isParameterDefined(h)&&(b+="left: "+h+"px ; ");!0===this.isParameterDefined(m)&&(b+="top: "+m+"px ; ");!0===this.isParameterDefined(k)?f=!0:k=0;!0===this.isParameterDefined(l)?f=!0:l=0;!0===this.isParameterDefined(q)&&
(f=!0,e=Math.PI/180*q);!0===this.isParameterDefined(r)&&(f=!0,d=c=r);!0===this.isParameterDefined(t)&&(f=!0,c=t);!0===this.isParameterDefined(a)&&(f=!0,d=a);1==f&&(b+="transform: matrix("+Math.cos(e)*c+" , "+Math.sin(e)*d+" , "+-Math.sin(e)*c+" , "+Math.cos(e)*d+" , "+k+" , "+l+" ) ; ",b+="-ms-transform: matrix("+Math.cos(e)*c+" , "+Math.sin(e)*d+" , "+-Math.sin(e)*c+" , "+Math.cos(e)*d+" , "+k+" , "+l+" ) ; ",b+="-webkit-transform: matrix("+Math.cos(e)*c+" , "+Math.sin(e)*d+" , "+-Math.sin(e)*c+
" , "+Math.cos(e)*d+" , "+k+" , "+l+" ) ; ",b+="-moz-transform: matrix("+Math.cos(e)*c+" , "+Math.sin(e)*d+" , "+-Math.sin(e)*c+" , "+Math.cos(e)*d+" , "+k+" , "+l+" ) ; ");return b};
biTurbo.proto.createTween=function(a,b,c){c=this.defaultParameter(c,0);switch(c){default:case 0:c="linear";break;case 1:c="ease-in";break;case 2:c="ease-out";break;case 3:c="ease-in-out";break;case 4:c="cubic-bezier(0.175, 0.885, 0.32, 1.275)";break;case 5:c="step-end"}this.writeClass(".tween_"+a,"transition: all "+b+"s "+c+" ; "+("-webkit-transition: all "+b+"s "+c+" ; ")+("-moz-transition: all "+b+"s "+c+" ; ")+("-o-transition: all "+b+"s "+c+" ; ")+("-ms-transition: all "+b+"s "+c+" ; "))};
biTurbo.proto.createDivElement=function(a,b,c,d){var e="display:block ; position:absolute ; ";a=this.defaultParameter(a,"");c=this.defaultParameter(c,"");d=this.defaultParameter(d,!1);var f="img_preload_"+a;var g="."+a;if(null===this.insertionPoint)this.a_print(" Error: You must define insertionPoint in HTML ");else{var h=document.getElementById(this.insertionPoint);""===b?(e+=" overflow: hidden; ",b="</div>"):(e+=" background: url("+b+") ; ",b='<img id="'+f+'" src="'+b+'" style="visibility: hidden ; display : block;" /></div>',
!0===this.addImagesToPreloadQueue&&this.imagesToLoad.push(f));this.writeClass(g,e+c);h.innerHTML+='<div id="'+a+'" class="'+a+'">'+b;!1===d&&this.elementsCreated.push(a)}};biTurbo.proto.createTextElement=function(a,b,c){var d=a+"_container",e=this.insertionPoint,f="."+a;this.createDivElement(d,"",1,0,0,"transparent");this.insertionPoint=d;d=document.getElementById(this.insertionPoint);this.writeClass(f,c);d.innerHTML+='<p id="'+a+'" class="'+a+'">'+b+"</p>";this.insertionPoint=e;this.elementsCreated.push(a)};
biTurbo.proto.createBorder=function(a,b){this.createDivElement("border_frame","","opacity:1 ; left:0px ; top:0px ; background-color:transparent ; width:"+(this.width-2*b)+"px ; height:"+(this.height-2*b)+"px ; "+("border-style: solid; border-color: "+a+" ; border-width: "+b+"px"),!0)};biTurbo.proto.setTimeLine=function(){this.timeLine=arguments;this.currentFrameIndex=0};
biTurbo.proto.nextFrameInTimeLine=function(a){var b=this;a=this.defaultParameter(a,.1);setTimeout(function(){b.currentFrameIndex<b.timeLine.length&&!1===biTurboProps.pauseAll&&!1===b.pauseThis&&(b.a_print(b.currentFrameIndex+": "+b.timeLine[b.currentFrameIndex]),b.gotoFrame(b.timeLine[b.currentFrameIndex]),b.currentFrameIndex++)},1E3*a)};biTurbo.proto.gotoFrame=function(a){window[a]()};
biTurbo.proto.setBTN=function(a,b,c,d){var e=this;a=this.getDomElement(a);c=this.defaultParameter(c,!1);d=this.defaultParameter(d,"");a.addEventListener("click",function(){e.userClickedFunction(b,c,d)});this.createClass("a_cursor","cursor: pointer;");this.applyClass(a,"a_cursor")};
biTurbo.proto.userClickedFunction=function(a,b,c){!0===b&&(this.pauseThis=biTurboProps.pauseAll=!0,window[c]());this.a_print('-- \n biTurboProps.pauseAll , this.pauseThis=true ; animation goes to frame "'+c+'" and invokes function: '+a+"()");window[a]()};biTurbo.proto.startWhenLoadedEnough=function(){var a=this;this.checkLoaded(a);addEventListener("loadedEnough",function(b){a.nextFrameInTimeLine()})};
biTurbo.proto.checkLoaded=function(a){if("function"===typeof Event)var b=new Event("loadedEnough");else b=document.createEvent("Event"),b.initEvent("loadedEnough",!0,!0);0<this.limitToWaitPreload?setTimeout(function(){var c,d=0,e=a.imagesToLoad.length;for(c=0;c<e;c++){var f=a.getDomElement(a.imagesToLoad[c]);!0===f.complete&&d++}a.a_print("-- \n imagesLoaded "+d+"/"+e);d===e?(a.a_print("-- \n preload complete"),dispatchEvent(b)):(a.limitToWaitPreload--,a.a_print("-- \n preload in progress: "+a.limitToWaitPreload),
a.checkLoaded(a))},200):(a.a_print("-- \n preloader timeOut"),dispatchEvent(b))};biTurbo.proto.defaultParameter=function(a,b){return void 0===a||null===a?b:a};biTurbo.proto.isParameterDefined=function(a){return void 0===a||null===a?!1:!0};biTurbo.proto.a_print=function(a){!0===biTurboProps.debug&&!0===this.isParameterDefined(a)&&console.log(a)};biTurbo.proto.getDomElement=function(a){"string"===typeof a.valueOf()&&(a=document.getElementById(a));return a};biTurbo.create=function(){return Object.create(this.proto)};
