var biTurboProps={debug:!0,clicked:!1};if("undefined"===typeof biTurbo)var biTurbo={};biTurbo.prototype={debug:!1,loop:0,height:0,width:0,insertionPoint:"",currentFrameIndex:0,timeLine:[],imagesToLoad:[],elementsCreated:[],limitToWaitPreload:4};biTurbo.prototype.initStyle=function(a){var b=document.createElement("style");b.type="text/css";b.appendChild(document.createTextNode(""));document.head.appendChild(b);console.log(""+this);console.log(""+a);this.a_print("                              biTurbo.js \n \n                                  by \n \n                         \u00c1ngel Quijada \u00c1lvarez \n \n   A lightweight JS animation library for fast banner ads development! \n ")};
biTurbo.prototype.writeClass=function(a,b){var c=document.createElement("style");c.type="text/css";document.getElementsByTagName("head")[0].appendChild(c);this.a_print("new CSS class : "+a+" : "+b);c.sheet.insertRule(a+"{"+b+"}",0)};biTurbo.prototype.applyClass=function(a,b){a=this.getDomElement(a);a.classList.add(b)};biTurbo.prototype.applyClassToAll=function(a){var b;for(b=0;b<this.elementsCreated.length;b++){var c=this.getDomElement(this.elementsCreated[b]);c.classList.add(a)}};
biTurbo.prototype.clearClassToAll=function(){var a;for(a=0;a<this.elementsCreated.length;a++){var b=this.getDomElement(this.elementsCreated[a]);this.clearClass(b)}};biTurbo.prototype.tweenClass=function(a,b,c,d){d=defaultParameter(d,0);a=this.getDomElement(a);var e=a.id,f="tween_"+c;setTimeout(function(){this.clearClass(a);applyClass(a,e);applyClass(a,b);applyClass(a,f)},1E3*d)};biTurbo.prototype.clearClass=function(a){a=this.getDomElement(a);var b=a.id;a.className="";this.applyClass(a,b)};
biTurbo.prototype.createClass=function(a,b){var c="";if(1>arguments.length)this.a_print("Error: createClass: no parameters");else{var d=arguments[0];var e=arguments[1];this.isParameterDefined(e)&&(c+=e+" ; ");this.writeClass("."+d,c)}};
biTurbo.prototype.acc_CSS=function(a,b,c,d,e){var f="";this.isParameterDefined(a)&&(f+="opacity: "+a+" ; ");this.isParameterDefined(b)&&(f+="left: "+b+"px ;");this.isParameterDefined(c)&&(f+="top: "+c+"px ;");this.isParameterDefined(d)&&(f+="width: "+d+"px ;");this.isParameterDefined(e)&&(f+="height: "+e+"px ;");return f};
biTurbo.prototype.tMatrix=function(a,b,c,d,e){var f="";!1===this.isParameterDefined(d)&&(d=0);!1===this.isParameterDefined(e)&&(e=0);if(this.isParameterDefined(b)||this.isParameterDefined(a)){var g=void 0===b||null===b?1:b;b=this.isParameterDefined(c)?c:b;if(void 0===a||null===a)a=0;a=Math.PI/180*a*5;f+="transform: matrix("+Math.cos(a)*g+" , "+Math.sin(a)*b+" , "+-Math.sin(a)*g+" , "+Math.cos(a)*b+" , "+d+" , "+e+" ) ; ";f+="-ms-transform: matrix("+Math.cos(a)*g+" , "+Math.sin(a)*b+" , "+-Math.sin(a)*
g+" , "+Math.cos(a)*b+" , "+d+" , "+e+" ) ; ";f+="-webkit-transform: matrix("+Math.cos(a)*g+" , "+Math.sin(a)*b+" , "+-Math.sin(a)*g+" , "+Math.cos(a)*b+" , "+d+" , "+e+" ) ; ";f+="-moz-transform: matrix("+Math.cos(a)*g+" , "+Math.sin(a)*b+" , "+-Math.sin(a)*g+" , "+Math.cos(a)*b+" , "+d+" , "+e+" ) ; "}return f};
biTurbo.prototype.createTween=function(a,b,c){c=this.defaultParameter(c,1);switch(c){default:c="linear";break;case 1:c="ease-in";break;case 2:c="ease-out";break;case 3:c="ease-in-out";break;case 4:c="cubic-bezier(0.175, 0.885, 0.32, 1.275)";break;case 5:c="step-end"}this.writeClass(".tween_"+a,"transition: all "+b+"s "+c+" ; "+("-webkit-transition: all "+b+"s "+c+" ; ")+("-moz-transition: all "+b+"s "+c+" ; ")+("-o-transition: all "+b+"s "+c+" ; ")+("-ms-transition: all "+b+"s "+c+" ; "))};
biTurbo.prototype.tweenClass=function(a,b,c,d){d=this.defaultParameter(d,0);a=this.getDomElement(a);var e=a.id,f="tween_"+c,g=this;setTimeout(function(){a.className="";g.applyClass(a,e);g.applyClass(a,b);g.applyClass(a,f)},1E3*d)};
biTurbo.prototype.createDivElement=function(a,b,c,d){a=this.defaultParameter(a,"");c=this.defaultParameter(c,"");d=this.defaultParameter(d,!1);var e="display:block ; position:absolute ; ",f="img_preload_"+a;console.log(this.insertionPoint);if(null===this.insertionPoint)this.a_print(" Error: You must define insertionPoint in HTML ");else{var g=document.getElementById(this.insertionPoint);""===b?(e+=" overflow: hidden; ",b="</div>"):(e+=" background: url("+b+") ; ",b='<img id="'+f+'" src="'+b+'" style="visibility: hidden ; display : block;" /></div>',
this.imagesToLoad.push(f));this.writeClass("."+a,e+c);g.innerHTML+='<div id="'+a+'" class="'+a+'">'+b;console.log("createDivElement: "+a+" : "+d);!1===d&&this.elementsCreated.push(a)}};biTurbo.prototype.createTextElement=function(a,b,c){var d=a+"_container",e=this.insertionPoint;this.createDivElement(d,"",1,0,0,"transparent");this.insertionPoint=d;d=document.getElementById(this.insertionPoint);this.writeClass("."+a,c);d.innerHTML+='<p id="'+a+'" class="'+a+'">'+b+"</p>";this.insertionPoint=e;this.elementsCreated.push(a)};
biTurbo.prototype.createBorder=function(a,b){this.createDivElement("border_frame","","opacity:1 ; left:0px ; top:0px ; background-color:transparent ; width:"+(this.width-2*b)+"px ; height:"+(this.height-2*b)+"px ; "+("border-style: solid; border-color: "+a+" ; border-width: "+b+"px"),!0)};biTurbo.prototype.setTimeLine=function(){this.timeLine=arguments;this.currentFrameIndex=0};
biTurbo.prototype.nextFrameInTimeLine=function(a){a=this.defaultParameter(a,.1);console.log("nextFrameInTimeLine :"+a);console.log(biTurboProps.clicked+" "+this.currentFrameIndex+" "+this.timeLine.length);var b=this;setTimeout(function(){b.currentFrameIndex<b.timeLine.length&&!1===biTurboProps.clicked&&(b.a_print(b.currentFrameIndex+": "+b.timeLine[b.currentFrameIndex]),b.gotoFrame(b.timeLine[b.currentFrameIndex]),b.currentFrameIndex++)},1E3*a)};biTurbo.prototype.gotoFrame=function(a){if(!1===biTurboProps.clicked)window[a]()};
biTurbo.prototype.setBTN=function(a,b,c){a=this.getDomElement(a);c=this.defaultParameter(c,this.timeLine[this.timeLine.length-1]);var d=this;a.addEventListener("click",function(){d.clickTag(b,c)});this.writeClass(".a_cursor","cursor: pointer;");this.applyClass(a,"a_cursor")};biTurbo.prototype.clickTag=function(a,b){biTurboProps.clicked=!0;this.a_print('-- \n biTurboProps.clicked=true ; animation goes to frame "'+b+'" and invokes function: '+a+"()");window[b]();window[a]()};
biTurbo.prototype.checkLoaded=function(){if(0<this.limitToWaitPreload){var a=this;setTimeout(function(){var b,c=0;for(b=0;b<a.imagesToLoad.length;b++){var d=a.getDomElement(a.imagesToLoad[b]);!0===d.complete&&c++}a.a_print("-- \n imagesLoaded "+c+"/"+a.imagesToLoad.length);c===a.imagesToLoad.length?a.nextFrameInTimeLine():(a.limitToWaitPreload--,a.checkLoaded())},333)}else a.a_print("-- \n preloader timeOut"),a.nextFrameInTimeLine()};
biTurbo.prototype.defaultParameter=function(a,b){return void 0===a||null===a?b:a};biTurbo.prototype.isParameterDefined=function(a){return void 0===a||null===a?!1:!0};biTurbo.prototype.a_print=function(a){!0===biTurboProps.debug&&!0===this.isParameterDefined(a)&&console.log(a)};biTurbo.prototype.getDomElement=function(a){"string"===typeof a.valueOf()&&(a=document.getElementById(a));return a};biTurbo.create=function(){return Object.create(this.prototype)};